/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Thrift
{
  public enum TReadType
  {
    DEFAULT = 1,
    STREAM = 2,
    PREAD = 3,
  }
}
